version: '3'
services:
    #Postgres DB
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB = simple_blog_api
    #api
    blogapi:
        depends_on:
          - postgres
        image: justinlalv/simpleblog    
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
          - '3000:3000'     
        environment:
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=6379
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=simple_blog_api