apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: simple-blog-api
        image: justinlalv/simple-blog-api
        ports:
            - containerPort: 3000
        env:
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service.yml
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: pgpassword
                   key: POSTGRES_PASSWORD      
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        